# © 2019 Netxillon Technologies.
# ------------------------------
# Author: Gurmukh Singh
# Email: trainings@netxillon.com
# Date: 22-06-2020
# ------------------------------

# You are free to use these as long as you acknowledge it back to the source and give due credit.

# ****************************************WARNING************************
# There is no guarantee for the use of these scripts/roles and the author
# is in no way liable for any damange caused by the use of these scripts.
# ************************************************************************
---

- name:         Update systemctl with recommended config
  sysctl:
    name:       "{{ item.name }}"
    value:      "{{ item.value }}"
    sysctl_set: yes
    state:      present
    reload:     yes
  with_items:
    - { name : "net.core.netdev_max_backlog", value: "6000" }
    - { name : "net.core.somaxconn", value: "16384" }
    - { name : "net.ipv4.ip_forward", value: "0" }
    - { name : "net.ipv4.conf.default.rp_filter", value: "1" }
    - { name : "net.ipv4.conf.default.accept_source_route", value: "0" }
    - { name : "net.ipv4.tcp_max_syn_backlog", value: "4000" }
    - { name : "net.ipv4.tcp_syncookies", value: "1" }
    - { name : "net.ipv4.tcp_sack", value: "0" }
    - { name : "net.ipv4.tcp_dsack", value: "0" }
    - { name : "net.ipv4.tcp_keepalive_time", value: "120" }
    - { name : "net.ipv4.tcp_keepalive_probes", value: "5" }
    - { name : "net.ipv4.tcp_keepalive_intvl", value: "15" }
    - { name : "net.ipv4.tcp_fin_timeout", value: "30" }
    - { name : "net.ipv4.tcp_rmem", value: "32768 436600 4193404" }
    - { name : "net.ipv4.tcp_wmem", value: "32768 436600 4193404" }
    - { name : "net.ipv4.tcp_retries2", value: "10" }
    - { name : "net.ipv4.tcp_synack_retries", value: "3" }
    - { name : "net.ipv4.tcp_max_tw_buckets", value: "8000" }
    - { name : "net.ipv4.tcp_tw_reuse", value: "1" }
    - { name : "net.ipv4.neigh.default.gc_interval", value: "3600" }
    - { name : "net.ipv4.neigh.default.gc_stale_time", value: "3600" }
    - { name : "net.ipv4.neigh.default.gc_thresh3", value: "5120" }
    - { name : "net.ipv4.neigh.default.gc_thresh2", value: "4096" }
    - { name : "net.ipv4.neigh.default.gc_thresh1", value: "2048" }
    - { name : "kernel.sysrq", value: "0" }
    - { name : "kernel.core_uses_pid", value: "1" }
    - { name : "vm.swappiness", value: "1" }
    - { name : "vm.dirty_background_ratio", value: "20" }
    - { name : "vm.dirty_ratio", value: "50" }
    - { name : "vm.max_map_count", value: "131070" }

