# © 2019 Netxillon Technologies.
# ------------------------------
# Author: Gurmukh Singh
# Email: trainings@netxillon.com
# Date: 22-06-2020
# ------------------------------

# You are free to use these as long as you acknowledge it back to the source and give due credit.

# ****************************************WARNING************************
# There is no guarantee for the use of these scripts/roles and the author
# is in no way liable for any damange caused by the use of these scripts.
# ************************************************************************

---
- name: Install Airflow PreReq
  yum:  name={{item}} state=installed
  with_items:
   - mysql-devel
   - openssl-devel
   - python-setuptools
   - python3
   - python3-devel
   - gcc
   - zlib-devel
   - bzip2-devel
   - ncurses-devel
   - sqlite-devel
   - cyrus-sasl-devel.x86_64

- pip:
    name: mysqlclient
    executable: "pip{{ pip_version }}"
    #state: forcereinstall
  become: True
- pip:
    name: cryptography
    executable: "pip{{ pip_version }}"
    #state: forcereinstall
  become: True
- pip:
    name: apache-airflow
    executable: "pip{{ pip_version }}"
    #state: forcereinstall
  become: True
- pip:
    name: apache-airflow[celery]
    executable: "pip{{ pip_version }}"
    #state: forcereinstall
    umask: "0022"
  become: True

